document.writeln("<ul class=\'Navigation\'>");		
document.writeln("<p>");
document.writeln("</p>");
document.writeln("			<li>");
document.writeln("				已加盟商家");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<a href=\'\'>已加盟企业商家</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'\'>已加盟学生商家</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				商家加盟申请");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<a href=\'\'>企业商家加盟申请</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'\'>学生商家加盟申请</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				管理员账号");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<a href=\'\'>账号申请</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'\'>修改密码</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'\'>账号管理</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				易点包车");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<a href=\'BusSearcher.html\'>我要坐车</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'TicketManagement.html\'>车票管理</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'CarRentalOrder.html\'>租车订单</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				公告栏");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<a href=\'CurrentAnnouncement.html\'>当前公告</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'HistoryAnnouncement.html\'>历史公告</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("		</ul>");